server:
  port: 5800
  servlet:
    context-path: /auth
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:5762/eureka
    register-with-eureka: true

---
spring:
  application:
    name: auth-service


link-gateway-oauth:
  issuer-uri: http://localhost:8081/realms/agrobrasil
  clientId: microservices
  clientSecret: Xpj2Rk966pp9PsjXQ5iXsV6PeBNpsomu
