server:
  port: 5800
  servlet:
    context-path: /auth
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://127.0.0.1:5762/eureka/}
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans	
---
spring:
  application:
    name: auth-service


link-gateway-oauth:
  issuer-uri: http://localhost:8081/realms/agrobrasil
  clientId: microservices
  clientSecret: Xpj2Rk966pp9PsjXQ5iXsV6PeBNpsomu
  keyloack-host: http://localhost:8081
