server:
  port: 5800
  forward-headers-strategy: framework
  servlet:
    context-path: /auth
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://127.0.0.1:5762/eureka/}
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/api/v2/spans}
---
spring:
  application:
    name: auth-service

springdoc:
  api-docs:
    version: OPENAPI_3_1
  cache:
    disabled: true

link-gateway-oauth:
  issuer-uri: ${KEYCLOAK_ISSUER:http://localhost:8081/realms/agrobrasil}
  clientId: microservices
  clientSecret: Xpj2Rk966pp9PsjXQ5iXsV6PeBNpsomu
  keyloack-host: ${KEYCLOAK_HOST:http://localhost:8081}
