server:
  port: 8080
  max-http-request-header-size: 32768
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:5762/eureka
  instance:
    preferIpAddress: true
logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionRouteLocator: INFO
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always    
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans	
---
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: eureka-server
          predicates:
            - Path=/eureka/web
          uri: http://localhost:5762

        - id: eureka-server-static
          predicates:
            - Path=/eureka/**
          uri: http://localhost:5762

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        #- id: openapi-proxy
        #  uri: http://backend-
        #  predicates:
        #    - Path=/demo-microservices/v3/api-docs/**
        #  filters:
        #    - RewritePath=/demo-microservices/v3/api-docs/(?<path>.*), /demo-microservices/$\{path}/v3/api-docs
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/agrobrasil
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

springdoc: 
  cache: 
   disabled: true
  api-docs:
   version: OPENAPI_3_1

  swagger-ui:
    use-root-path: true
    oauth:
      clientId: microservices
      clientSecret: Xpj2Rk966pp9PsjXQ5iXsV6PeBNpsomu
    oAuthFlow:
      authorizationUrl: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/auth
      tokenUrl: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token
