server:
  port: 8080
  max-http-request-header-size: 32768
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://127.0.0.1:5762/eureka/}
  instance:
    preferIpAddress: true
logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionRouteLocator: INFO
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/api/v2/spans}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: eureka-server
          predicates:
            - Path=/eureka/web
          uri: ${EUREKA_CLIENT_SERVICEURL_HOST:http://localhost:5762}

        - id: eureka-server-static
          predicates:
            - Path=/eureka/**
          uri: ${EUREKA_CLIENT_SERVICEURL_HOST:http://localhost:5762}

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: visita-service
          uri: lb://visita-service
          predicates:
            - Path=/visita/**

        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER:http://localhost:8081/realms/agrobrasil}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    oauth:
      clientId: microservices
      clientSecret: Xpj2Rk966pp9PsjXQ5iXsV6PeBNpsomu
    oAuthFlow:
      authorizationUrl: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/auth
      tokenUrl: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token
    urls:
      - name: auth
        url: /v3/api-docs/auth
      - name: viasoft
        url: /v3/api-docs/viasoft